import type { Metadata } from "next";
import { PageHero } from "@/components/page-hero";
import { ProfessionalConsultationForm } from "@/components/professional-consultation-form";
import { createPageMetadata } from "@/lib/metadata";
import { siteConfig } from "@/lib/site-config";
import { getPublicServiceBySlug } from "@/data/services";
import { buildWhatsAppUrl } from "@/lib/contact-links";
export const metadata: Metadata = createPageMetadata("Consulta profesional", "Solicitud de evaluación para consulta, revisión, patrocinio o defensa profesional.", "/consulta-profesional/");
export default async function ConsultationPage({ searchParams }: { searchParams: Promise<{ service?: string | string[] }> }) { const requested = (await searchParams).service; const slug = typeof requested === "string" ? requested : undefined; const selectedService = slug ? getPublicServiceBySlug(slug) : undefined; return <><PageHero eyebrow="Atención profesional" title="Cuando el caso requiere criterio y estrategia" description="Prepare una solicitud para orientación, revisión, redacción, análisis de expediente, videollamada, patrocinio, defensa o evaluación técnica." status="Atención corporativa directa" /><section className="content-section consultation-layout"><div className="container"><div className="consultation-steps"><article><span>01</span><h2>Prepare</h2><p>Indique materia, jurisdicción, urgencia y el objetivo de la consulta sin adjuntar documentos.</p></article><article><span>02</span><h2>Revise</h2><p>El sistema estructurará su mensaje para ser enviado a través de WhatsApp o correo electrónico.</p></article><article><span>03</span><h2>Coordine</h2><p>La administración confirmará disponibilidad, alcance y condiciones por el mismo canal.</p></article></div><ProfessionalConsultationForm {...(selectedService ? { selectedService: { slug: selectedService.slug, title: selectedService.title } } : {})} /><aside className="institutional-pending"><h2>Canales institucionales</h2><p>Correo: <a href={`mailto:${siteConfig.contact.email}`}>{siteConfig.contact.email}</a>.</p><p>WhatsApp Business: <a href={buildWhatsAppUrl()}>{siteConfig.contact.whatsapp.display}</a>.</p><p>El formulario construye su mensaje y abre su aplicación para enviarlo. No almacena información en nuestros servidores ni envía datos automáticamente. No adjunte archivos ni comparta información sensible por estos canales sin indicación previa.</p></aside></div></section></>; }
