// @vitest-environment node
import{mkdtemp,readFile,rm}from"node:fs/promises";import{tmpdir}from"node:os";import path from"node:path";import{afterEach,describe,expect,it}from"vitest";import{InMemoryJurisprudencePublicSearchIndexRepository}from"@/lib/in-memory-jurisprudence-public-search-index-repository";import{createJurisprudencePublicSearchIndexService}from"@/lib/jurisprudence-public-search-index-service";import{evaluateJurisprudencePublicSearchReadiness}from"@/lib/jurisprudence-public-search-readiness";import{buildJurisprudenceSearchDocument,normalizeJurisprudenceSearchText}from"@/lib/jurisprudence-search-normalization";import{jurisprudenceSearchDocumentSchema,jurisprudenceSearchQuerySchema,prepareJurisprudenceSearchDocumentCommandSchema}from"@/lib/schemas/jurisprudence-public-search";import{SqliteJurisprudencePublicSearchIndexRepository}from"@/lib/sqlite-jurisprudence-public-search-index-repository";import type{JurisprudencePublicReadModel,JurisprudencePublicReadModelRepository}from"@/types/jurisprudence-public-exposure";import type{JurisprudencePublicSearchDependencies,JurisprudencePublicSearchIndexService,JurisprudenceSearchIndexRepository,JurisprudenceSearchLogEvent,JurisprudenceSearchQuery}from"@/types/jurisprudence-public-search";
const NOW="2026-07-30T12:00:00.000Z",context={requestId:"request-11m",actorReference:"actor-opaco-11m",requestedAt:NOW};
function publicModel(n:number,overrides:Partial<JurisprudencePublicReadModel>={}):JurisprudencePublicReadModel{return Object.freeze({publicRecordId:`public-${n}`,projectionId:`projection-${n}`,recordId:`record-${n}`,recordVersion:1,slug:`resolucion-ficticia-${n}`,title:`Resolución ficticia ${n}`,caseNumber:`EXP-FICTICIO-11M-00${n}`,resolutionNumber:`RES-FICTICIA-00${n}`,resolutionType:n%2?"sentencia":"auto",institutionName:n%2?"INSTITUCION-A":"INSTITUCION-B",issuingBody:n%2?"ORGANO-A":"ORGANO-B",matter:n%2?"civil":"laboral",issuedAt:`2026-01-0${n}`,summary:`Resumen público ficticio número ${n}.`,sourceName:"FUENTE-FICTICIA",sourceDocumentId:`DOC-FICTICIO-${n}`,publicStatus:"exposed",preparedAt:NOW,exposedAt:NOW,withdrawnAt:null,supersededAt:null,publicRevision:1,exposedPublicly:true,indexed:false,deployed:false,...overrides})}
class FixtureReadModels implements JurisprudencePublicReadModelRepository{readonly values=new Map<string,JurisprudencePublicReadModel>();#closed=false;constructor(...items:JurisprudencePublicReadModel[]){items.forEach((x)=>this.values.set(x.publicRecordId,x))}async findById(id:string){if(this.#closed)throw new Error("closed");return this.values.get(id)??null}async findActiveByRecordVersion(id:string,v:number){return[...this.values.values()].find((x)=>x.recordId===id&&x.recordVersion===v&&x.publicStatus==="exposed")??null}async findActiveBySlug(slug:string){return[...this.values.values()].find((x)=>x.slug===slug&&x.publicStatus==="exposed")??null}async listByRecord(id:string){return[...this.values.values()].filter((x)=>x.recordId===id)}async close(){this.#closed=true}}
const services:JurisprudencePublicSearchIndexService[]=[];
const repositoryKinds:readonly ("memory"|"sqlite")[]=["memory","sqlite"];
afterEach(async()=>{await Promise.all(services.splice(0).map((x)=>x.close()))});
function system(kind:"memory"|"sqlite"="memory",file=":memory:",models=[publicModel(1),publicModel(2),publicModel(3)]){const source=new FixtureReadModels(...models);const repository:JurisprudenceSearchIndexRepository=kind==="memory"?new InMemoryJurisprudencePublicSearchIndexRepository():new SqliteJurisprudencePublicSearchIndexRepository(file);let id=0;const logs:JurisprudenceSearchLogEvent[]=[];const service=createJurisprudencePublicSearchIndexService({publicReadModels:source,indexRepository:repository,now:()=>NOW,generateId:()=>`generated-11m-${++id}`,logger:{log:e=>logs.push(e)}} satisfies JurisprudencePublicSearchDependencies);services.push(service);return{service,source,logs}}
const prepare=(n=1,key=`prepare-key-${n}`)=>({context,publicRecordId:`public-${n}`,expectedPublicRevision:1,idempotencyKey:key});
async function prepareAndIndex(service:JurisprudencePublicSearchIndexService,n=1){const p=await service.prepare(prepare(n));return service.index({context,searchDocumentId:p.document.searchDocumentId,expectedRevision:1,idempotencyKey:`index-key-${n}`})}
const query=(overrides:Partial<JurisprudenceSearchQuery>={}):JurisprudenceSearchQuery=>({context,filters:{},sort:"relevance",offset:0,limit:20,...overrides});
describe("fase 11.M: índice interno y puerta de consulta",()=>{
 describe("contratos y documento",()=>{
  it("acepta comandos estrictos y rechaza propiedades desconocidas, estados y bypass",()=>{expect(prepareJurisprudenceSearchDocumentCommandSchema.safeParse(prepare()).success).toBe(true);expect(prepareJurisprudenceSearchDocumentCommandSchema.safeParse({...prepare(),force:true}).success).toBe(false);const d=buildJurisprudenceSearchDocument({id:"document-11m",readModel:publicModel(1),preparedAt:NOW});expect(jurisprudenceSearchDocumentSchema.safeParse({...d,status:"public_live"}).success).toBe(false);expect(jurisprudenceSearchDocumentSchema.safeParse({...d,authorizationCaseId:"interno"}).success).toBe(false)});
  it("rechaza IDs, fechas, revisiones, límites y consultas inválidas sin excepción nativa",()=>{expect(()=>jurisprudenceSearchQuerySchema.safeParse({...query(),context:{...context,requestedAt:"fecha"},limit:0})).not.toThrow();expect(jurisprudenceSearchQuerySchema.safeParse({...query(),limit:51}).success).toBe(false);expect(prepareJurisprudenceSearchDocumentCommandSchema.safeParse({...prepare(),publicRecordId:"",expectedPublicRevision:0}).success).toBe(false)});
  it("omite filtros opcionales ausentes y conserva exclusivamente fechas presentes",()=>{const empty=jurisprudenceSearchQuerySchema.parse(query());expect("issuedFrom" in empty.filters).toBe(false);expect("issuedTo" in empty.filters).toBe(false);const from=jurisprudenceSearchQuerySchema.parse(query({filters:{issuedFrom:"2026-01-01"}}));expect(from.filters.issuedFrom).toBe("2026-01-01");expect("issuedTo" in from.filters).toBe(false);const to=jurisprudenceSearchQuerySchema.parse(query({filters:{issuedTo:"2026-01-31"}}));expect(to.filters.issuedTo).toBe("2026-01-31");expect("issuedFrom" in to.filters).toBe(false);const both=jurisprudenceSearchQuerySchema.parse(query({filters:{issuedFrom:"2026-01-01",issuedTo:"2026-01-31"}}));expect(both.filters).toMatchObject({issuedFrom:"2026-01-01",issuedTo:"2026-01-31"});const invalid=jurisprudenceSearchQuerySchema.safeParse(query({filters:{issuedFrom:"2026-02-01",issuedTo:"2026-01-31"}}));expect(invalid.success).toBe(false);if(!invalid.success)expect(invalid.error.issues.map((issue)=>issue.path)).toContainEqual(["filters","issuedTo"]);expect(jurisprudenceSearchQuerySchema.safeParse({context,filters:{unknownFilter:"value"},sort:"relevance",offset:0,limit:20}).success).toBe(false)});
  it("construye solo desde 11.L, determinísticamente y sin alterar el original",()=>{const source=publicModel(1),a=buildJurisprudenceSearchDocument({id:"document-11m",readModel:source,preparedAt:NOW}),b=buildJurisprudenceSearchDocument({id:"document-11m",readModel:source,preparedAt:NOW});expect(a).toEqual(b);expect(source.title).toBe("Resolución ficticia 1");expect(Object.keys(a)).not.toContain("projectionId");expect(a.status).toBe("prepared_internal");expect(a.publiclySearchable).toBe(false)});
  it("normaliza de forma determinista sin IA ni inferencias",()=>{expect(normalizeJurisprudenceSearchText("  Resolución   ÁRBITRAL ")).toBe("resolucion arbitral");expect(normalizeJurisprudenceSearchText("Árbitral")).toBe(normalizeJurisprudenceSearchText("arbitral"))});
 });
 describe("preparación, indexación y consulta",()=>{
  it("no indexa automáticamente y la preparación no es consultable",async()=>{const{service}=system();await service.prepare(prepare());expect((await service.search(query())).items).toHaveLength(0)});
  it("indexa ficticiamente e impide doble indexación",async()=>{const{service}=system();const v=await prepareAndIndex(service);expect(v.document.status).toBe("indexed_internal");expect(v.realSearchIndex).toBe(false);await expect(service.index({context,searchDocumentId:v.document.searchDocumentId,expectedRevision:2,idempotencyKey:"second-index-key"})).rejects.toMatchObject({code:"DOCUMENT_ALREADY_INDEXED"})});
  it("busca exactamente por expediente y resolución con ranking explicable",async()=>{const{service}=system();await prepareAndIndex(service,1);expect((await service.search(query({text:"EXP-FICTICIO-11M-001"}))).items[0]?.matchedBy).toContain("case_exact");expect((await service.search(query({text:"RES-FICTICIA-001"}))).items[0]?.matchedBy).toContain("resolution_exact")});
  it("busca por título y términos normalizados",async()=>{const{service}=system();await prepareAndIndex(service,1);expect((await service.search(query({text:"Resolución ficticia 1"}))).items[0]?.matchedBy).toContain("title_exact");expect((await service.search(query({text:"publico ficticio"}))).total).toBe(1)});
  it("combina filtros y rango de fechas",async()=>{const{service}=system();await prepareAndIndex(service,1);await prepareAndIndex(service,2);const r=await service.search(query({filters:{institutionName:"INSTITUCION-A",matter:"civil",issuedFrom:"2026-01-01",issuedTo:"2026-01-01"}}));expect(r.items.map((x)=>x.publicRecordId)).toEqual(["public-1"])});
  it("ordena de forma estable y desempata por identificador",async()=>{const models=[publicModel(1,{issuedAt:"2026-01-01"}),publicModel(2,{issuedAt:"2026-01-01"})],{service}=system("memory",":memory:",models);await prepareAndIndex(service,1);await prepareAndIndex(service,2);const ids=(await service.search(query({sort:"issued_desc"}))).items.map((x)=>x.searchDocumentId);expect(ids).toEqual([...ids].sort())});
  it("pagina sin duplicados y admite resultado vacío",async()=>{const{service}=system();await prepareAndIndex(service,1);await prepareAndIndex(service,2);await prepareAndIndex(service,3);const a=await service.search(query({limit:2})),b=await service.search(query({offset:2,limit:2}));expect(new Set([...a.items,...b.items].map((x)=>x.searchDocumentId)).size).toBe(3);expect((await service.search(query({text:"sin-coincidencia"}))).items).toEqual([])});
  it("la consulta no muta revisión ni historial",async()=>{const{service}=system();const d=await prepareAndIndex(service);const before=await service.getHistory({context,recordId:d.document.recordId});await service.search(query({text:"ficticia"}));expect(await service.getHistory({context,recordId:d.document.recordId})).toEqual(before)});
 });
 describe("idempotencia, retiro y supersesión",()=>{
  it("repite idempotentemente y rechaza key con payload distinto",async()=>{const{service}=system();expect(await service.prepare(prepare())).toEqual(await service.prepare(prepare()));await expect(service.prepare(prepare(2,"prepare-key-1"))).rejects.toMatchObject({code:"IDEMPOTENCY_CONFLICT"})});
  it("rechaza conflicto de revisión",async()=>{const{service}=system();const p=await service.prepare(prepare());await expect(service.index({context,searchDocumentId:p.document.searchDocumentId,expectedRevision:2,idempotencyKey:"revision-conflict-key"})).rejects.toMatchObject({code:"REVISION_CONFLICT"})});
  it("retira, conserva historial y deja de consultar",async()=>{const{service}=system();const i=await prepareAndIndex(service),w=await service.withdraw({context,searchDocumentId:i.document.searchDocumentId,expectedRevision:2,reason:"institutional_withdrawal",idempotencyKey:"withdraw-key-11m"});expect(w.document.status).toBe("withdrawn");expect((await service.search(query())).items).toHaveLength(0);expect(await service.getHistory({context,recordId:i.document.recordId})).toHaveLength(3)});
  it("supersede exige nueva versión y no hereda indexación",async()=>{const old=publicModel(1),replacement=publicModel(4,{publicRecordId:"public-4",recordId:old.recordId,recordVersion:2,publicRevision:1}),{service}=system("memory",":memory:",[old,replacement]);const i=await prepareAndIndex(service,1),s=await service.supersede({context,searchDocumentId:i.document.searchDocumentId,expectedRevision:2,replacementPublicRecordId:"public-4",replacementExpectedPublicRevision:1,idempotencyKey:"supersede-key-11m"});expect(s.document.status).toBe("superseded");expect((await service.search(query())).total).toBe(0);const next=await service.prepare({context,publicRecordId:"public-4",expectedPublicRevision:1,idempotencyKey:"prepare-new-version"});expect(next.document.status).toBe("prepared_internal")});
 });
 describe("persistencia, lifecycle, logging y readiness",()=>{
  it.each(repositoryKinds)("mantiene comportamiento equivalente en %s",async(kind)=>{const{service}=system(kind);const v=await prepareAndIndex(service);expect((await service.get({context,searchDocumentId:v.document.searchDocumentId})).document).toEqual(v.document)});
  it("reabre SQLite temporal y limpia auxiliares",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"buholex-11m-")),db=path.join(dir,"search.sqlite");try{const x=system("sqlite",db);const v=await prepareAndIndex(x.service);await x.service.close();services.splice(services.indexOf(x.service),1);const y=system("sqlite",db);expect((await y.service.get({context,searchDocumentId:v.document.searchDocumentId})).document.status).toBe("indexed_internal")}finally{await Promise.all(services.splice(0).map((x)=>x.close()));await rm(dir,{recursive:true,force:true})}});
  it("cierra idempotentemente y falla seguro después",async()=>{const{service}=system();await service.close();await service.close();await expect(service.search(query())).rejects.toMatchObject({code:"RESOURCE_CLOSED"})});
  it("limita logs a metadatos seguros",async()=>{const{service,logs}=system();await prepareAndIndex(service);await service.search(query({text:"consulta secreta"}));expect(JSON.stringify(logs)).not.toContain("consulta secreta");expect(Object.keys(logs.at(-1)??{}).sort()).toEqual(["operation","requestId","resultCode","resultCount","timestamp"].sort())});
  it("mantiene readiness productivo en default deny",()=>{expect(evaluateJurisprudencePublicSearchReadiness()).toMatchObject({searchIndexArchitectureReady:true,internalSearchReady:true,realSearchIndexPresent:false,publicSearchConnected:false,searchEndpointMounted:false,searchUiConnected:false,externalIndexingEnabled:false,sitemapConnected:false,robotsModified:false,authenticationReal:false,published:false,deployed:false,overrideSupported:false})});
 });
 describe("barreras estáticas y preservación",()=>{
  it("no crea rutas, UI, Auth0 ni conexión con jurisprudencia",async()=>{const root=process.cwd();await expect(readFile(path.join(root,"app","api"))).rejects.toBeDefined();expect((await readFile(path.join(root,"package.json"),"utf8"))).not.toContain("@auth0/nextjs-auth0");const page=await readFile(path.join(root,"app","jurisprudencia","page.tsx"),"utf8");expect(page).not.toMatch(/public-search|search-index/)});
  it("mantiene React 19.1.1 y sitemap/robots sin integración del índice",async()=>{const root=process.cwd(),pkg=await readFile(path.join(root,"package.json"),"utf8");expect(pkg).toContain('"react": "19.1.6"');expect(pkg).toContain('"react-dom": "19.1.6"');expect(await readFile(path.join(root,"app","sitemap.ts"),"utf8")).not.toMatch(/public-search|search-index/);expect(await readFile(path.join(root,"app","robots.ts"),"utf8")).not.toMatch(/public-search|search-index/)});
  it("preserva SRV-WEB-001 y BL-LEG-CON-001",async()=>{const root=process.cwd(),servicesText=await readFile(path.join(root,"data","services.ts"),"utf8"),catalog=await readFile(path.join(root,"data","template-catalog.ts"),"utf8");expect(servicesText).toContain("allowsImmediatePayment: false");expect(servicesText).toContain("published: false");expect(catalog).toContain('availabilityStatus: "editorial_preview"');expect(catalog).toContain("publicDownloadAuthorized: false")});
 });
});
