// @vitest-environment node
import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { InMemoryJurisprudencePublicExposureRepository, InMemoryJurisprudencePublicReadModelRepository } from "@/lib/in-memory-jurisprudence-public-exposure-repository";
import { createJurisprudencePublicExposureService } from "@/lib/jurisprudence-public-exposure-service";
import { evaluateJurisprudencePublicExposureReadiness } from "@/lib/jurisprudence-public-exposure-readiness";
import { buildJurisprudencePublicReadModel } from "@/lib/jurisprudence-public-read-model-builder";
import { evaluateJurisprudencePublicExposureCommandSchema, jurisprudencePublicReadModelSchema } from "@/lib/schemas/jurisprudence-public-exposure";
import { SqliteJurisprudencePublicExposureRepository, SqliteJurisprudencePublicReadModelRepository } from "@/lib/sqlite-jurisprudence-public-exposure-repository";
import { JURISPRUDENCE_PUBLICATION_AUTHORIZATION_REQUIRED_CONDITIONS } from "@/types/jurisprudence-publication-authorization";
import type { JurisprudencePublicExposureDependencies, JurisprudencePublicExposureRepository, JurisprudencePublicExposureService, JurisprudencePublicReadModelRepository } from "@/types/jurisprudence-public-exposure";
import type { JurisprudencePrivacyReviewStatus, SourceRightsStatus } from "@/types/jurisprudence-publication-governance";

const NOW="2026-07-30T12:00:00.000Z",context={requestId:"request-11l",actorReference:"actor-opaco-11l",requestedAt:NOW};
function foundation(){
 let recordVersion=1; let projectionStatus:"active_internal"|"withdrawn"|"superseded"="active_internal";let authorizationStatus:"authorized"|"revoked"|"superseded"="authorized";let rights:SourceRightsStatus="public_display_permitted";let privacy:JurisprudencePrivacyReviewStatus="approved_for_public_projection";
 const projection={projectionId:"projection-11l",executionId:"execution-11l",authorizationCaseId:"authorization-11l",recordId:"record-11l",recordVersion:1,status:projectionStatus,slug:"resolucion-ficticia-11l",title:"Resolución ficticia 11.L",caseNumber:"EXP-FICTICIO-11L-001",resolutionNumber:"RESOLUCION-FICTICIA-11L-001",resolutionType:"sentencia",institutionName:"INSTITUCION-DE-PRUEBA",issuingBody:"ORGANO-JURISDICCIONAL-DE-PRUEBA",matter:"MATERIA-FICTICIA",issuedAt:"2026-01-01",summary:"Resumen público estrictamente ficticio.",sourceName:"FUENTE-FICTICIA-AUTORIZADA",sourceDocumentId:"DOC-FICTICIO-11L",generatedAt:NOW,updatedAt:NOW,exposedPublicly:false as const,deployed:false as const};
 return {setRecordVersion:(v:number)=>{recordVersion=v},setProjectionStatus:(v:typeof projectionStatus)=>{projectionStatus=v},setAuthorizationStatus:(v:typeof authorizationStatus)=>{authorizationStatus=v},setRights:(v:SourceRightsStatus)=>{rights=v},setPrivacy:(v:JurisprudencePrivacyReviewStatus)=>{privacy=v},
 api:{async getInternalRecord(){return{requestId:"request",record:{id:"record-11l",recordVersion}}}},
 execution:{async getExecution(){return{execution:{executionId:"execution-11l",recordId:"record-11l",recordVersion:1,editorialCaseId:"editorial-11l",publicationDossierId:"dossier-11l",authorizationCaseId:"authorization-11l",projectionId:"projection-11l",status:"executed" as const,version:1,executedAt:NOW,executedByReference:"actor-opaco",withdrawnAt:null,withdrawalReason:null,supersededAt:null,supersededByRecordVersion:null,createdAt:NOW,updatedAt:NOW,publicationExecuted:true,deployed:false as const},projection:{...projection,status:projectionStatus},current:true,publicationExecuted:true,publicProjectionExposed:false as const,deployed:false as const}}},
 authorization:{async getAuthorizationCase(){return{authorizationCase:{authorizationCaseId:"authorization-11l",publicationDossierId:"dossier-11l",recordId:"record-11l",recordVersion:1,decision:"authorize" as const,status:authorizationStatus,institutionalAuthorityRef:"authority-opaca",decisionRef:"decision-opaca",authorizationScopeRef:"scope-opaco",decidedAt:NOW,effectiveFrom:NOW,expiresAt:"2027-01-01T00:00:00.000Z",reasons:[],blockers:[],conditions:JURISPRUDENCE_PUBLICATION_AUTHORIZATION_REQUIRED_CONDITIONS,version:1,createdAt:NOW,updatedAt:NOW,revokedAt:null,supersededAt:null,publicationAuthorizationGranted:authorizationStatus==="authorized",publicationExecuted:false as const},authorizationCurrent:authorizationStatus==="authorized",publicationAuthorizationGranted:authorizationStatus==="authorized",publicationExecuted:false as const}}},
 governance:{async getDossier(){return{dossier:{dossierId:"dossier-11l",recordId:"record-11l",recordVersion:1,editorialCaseId:"editorial-11l",editorialCaseVersion:1,sourceBindingIds:["binding-11l"],provenanceAssessment:{assessmentId:"prov-11l",status:"verified" as const,assessedAt:NOW},integrityAssessment:{assessmentId:"integrity-11l",status:"checksum_verified" as const,assessedAt:NOW},rightsAssessment:{assessmentId:"rights-11l",status:rights,assessedAt:NOW},privacyAssessment:{assessmentId:"privacy-11l",status:privacy,riskCategories:[],otherRiskReference:null,assessedAt:NOW},publicProjectionAssessment:{assessmentId:"projection-assessment-11l",status:"approved" as const,assessedAt:NOW},institutionalOwnerReference:"owner-opaco",status:"complete_for_authorization_evaluation" as const,version:1,createdAt:NOW,updatedAt:NOW,supersededAt:null,closedAt:null},evaluation:{decision:"ready_for_authorization_evaluation" as const,conditions:["institutional_authorization_required" as const],publicationAuthorizationGranted:false as const,publicationExecuted:false as const}}}}
 };
}
const closers:JurisprudencePublicExposureService[]=[];afterEach(async()=>{await Promise.all(closers.splice(0).map((x)=>x.close()))});
function system(kind:"memory"|"sqlite"="memory",db=":memory:"){
 const f=foundation();let exposure:JurisprudencePublicExposureRepository;let read:JurisprudencePublicReadModelRepository;
 if(kind==="memory"){const source=new InMemoryJurisprudencePublicExposureRepository();exposure=source;read=new InMemoryJurisprudencePublicReadModelRepository(source)}else{const source=new SqliteJurisprudencePublicExposureRepository(db);exposure=source;read=new SqliteJurisprudencePublicReadModelRepository(source)}
 let id=0;const service=createJurisprudencePublicExposureService({...f,exposureRepository:exposure,readModelRepository:read,now:()=>NOW,generateId:()=>`generated-11l-${++id}`} satisfies JurisprudencePublicExposureDependencies);closers.push(service);return{...f,service};
}
const evaluate={context,executionId:"execution-11l",expectedRecordVersion:1};const prepare={...evaluate,idempotencyKey:"prepare-key-11l"};
describe("fase 11.L: read model público y puerta de exposición",()=>{
 describe("contratos y lista blanca",()=>{
  it("acepta comandos válidos y rechaza propiedades desconocidas",()=>{expect(evaluateJurisprudencePublicExposureCommandSchema.safeParse(evaluate).success).toBe(true);expect(evaluateJurisprudencePublicExposureCommandSchema.safeParse({...evaluate,force:true}).success).toBe(false)});
  it("rechaza identificadores, fechas y versiones inválidas sin excepción nativa",()=>{expect(()=>evaluateJurisprudencePublicExposureCommandSchema.safeParse({...evaluate,executionId:"",expectedRecordVersion:0,context:{...context,requestedAt:"fecha"}})).not.toThrow();expect(evaluateJurisprudencePublicExposureCommandSchema.safeParse({...evaluate,executionId:""}).success).toBe(false)});
  it("rechaza estado y campos internos no permitidos",()=>{const projection={projectionId:"projection",executionId:"execution",authorizationCaseId:"authorization",recordId:"record",recordVersion:1,status:"active_internal" as const,slug:"slug-valido",title:"Título",caseNumber:"Caso",resolutionNumber:"Resolución",resolutionType:"Tipo",institutionName:"Institución",issuingBody:"Órgano",matter:"Materia",issuedAt:"2026-01-01",summary:"Resumen",sourceName:"Fuente",sourceDocumentId:null,generatedAt:NOW,updatedAt:NOW,exposedPublicly:false as const,deployed:false as const};const m=buildJurisprudencePublicReadModel({publicRecordId:"public-11l",projection,preparedAt:NOW});expect(jurisprudencePublicReadModelSchema.safeParse({...m,notes:"internas"}).success).toBe(false);expect(jurisprudencePublicReadModelSchema.safeParse({...m,publicStatus:"published"}).success).toBe(false)});
  it("construye de forma determinista solo la lista blanca",()=>{const projection={projectionId:"p-11l",executionId:"e-11l",authorizationCaseId:"a-11l",recordId:"r-11l",recordVersion:1,status:"active_internal" as const,slug:"slug-publico",title:"Título",caseNumber:"Caso",resolutionNumber:"Resolución",resolutionType:"Tipo",institutionName:"Institución",issuingBody:"Órgano",matter:"Materia",issuedAt:"2026-01-01",summary:"Resumen",sourceName:"Fuente",sourceDocumentId:null,generatedAt:NOW,updatedAt:NOW,exposedPublicly:false as const,deployed:false as const};const a=buildJurisprudencePublicReadModel({publicRecordId:"public-11l",projection,preparedAt:NOW});expect(a).toEqual(buildJurisprudencePublicReadModel({publicRecordId:"public-11l",projection,preparedAt:NOW}));expect(a.exposedPublicly).toBe(false);expect(Object.keys(a)).not.toContain("authorizationCaseId")});
 });
 describe("evaluación, preparación y exposición ficticia",()=>{
  it("evalúa favorablemente sin persistir",async()=>{const{service}=system();expect(await service.evaluateExposure(evaluate)).toEqual({status:"ready",blockers:[],realPublicExposure:false});await expect(service.getPublicReadModel({context,publicRecordId:"generated-11l-1"})).rejects.toMatchObject({code:"NOT_FOUND"})});
  it("bloquea ejecución, autorización, retiro, versión, derechos y privacidad inválidos",async()=>{for(const mutate of [(x:ReturnType<typeof system>)=>x.setProjectionStatus("withdrawn"),(x:ReturnType<typeof system>)=>x.setAuthorizationStatus("revoked"),(x:ReturnType<typeof system>)=>x.setRecordVersion(2),(x:ReturnType<typeof system>)=>x.setRights("restricted"),(x:ReturnType<typeof system>)=>x.setPrivacy("in_review")]){const x=system();mutate(x);expect((await x.service.evaluateExposure(evaluate)).status).toBe("blocked")}});
  it("prepara sin exponer e idempotentemente",async()=>{const{service}=system();const a=await service.preparePublicReadModel(prepare),b=await service.preparePublicReadModel(prepare);expect(b).toEqual(a);expect(a.readModel.publicStatus).toBe("prepared_internal");expect(a.realPublicExposure).toBe(false)});
  it("expone solo el agregado ficticio y evita doble exposición",async()=>{const{service}=system();const p=await service.preparePublicReadModel(prepare);const exposed=await service.expose({context,publicRecordId:p.readModel.publicRecordId,expectedRevision:1,idempotencyKey:"expose-key-11l"});expect(exposed.readModel.exposedPublicly).toBe(true);expect(exposed.realPublicExposure).toBe(false);expect((await service.evaluateExposure(evaluate)).status).toBe("already_exposed")});
  it("detecta conflictos de revisión e idempotencia",async()=>{const{service}=system();const p=await service.preparePublicReadModel(prepare);await expect(service.expose({context,publicRecordId:p.readModel.publicRecordId,expectedRevision:2,idempotencyKey:"bad-revision-11l"})).rejects.toMatchObject({code:"REVISION_CONFLICT"});await expect(service.preparePublicReadModel({...prepare,executionId:"other-execution"})).rejects.toMatchObject({code:"IDEMPOTENCY_CONFLICT"})});
 });
 describe("retiro, supersesión y persistencia",()=>{
  it("retira idempotentemente sin borrar historial",async()=>{const{service}=system();const p=await service.preparePublicReadModel(prepare),e=await service.expose({context,publicRecordId:p.readModel.publicRecordId,expectedRevision:1,idempotencyKey:"expose-key-11l"});const command={context,publicRecordId:e.readModel.publicRecordId,expectedRevision:2,reason:"institutional_withdrawal" as const,idempotencyKey:"withdraw-key-11l"};expect((await service.withdraw(command)).readModel.publicStatus).toBe("withdrawn");expect((await service.withdraw(command)).exposure.revision).toBe(3);expect((await service.getHistory({context,recordId:"record-11l"}))).toHaveLength(3)});
  it("supersede exige nueva versión y no hereda exposición",async()=>{const x=system();const p=await x.service.preparePublicReadModel(prepare);x.setRecordVersion(2);const s=await x.service.supersede({context,publicRecordId:p.readModel.publicRecordId,expectedRevision:1,newRecordVersion:2,idempotencyKey:"supersede-key-11l"});expect(s.readModel.publicStatus).toBe("superseded");expect(s.readModel.exposedPublicly).toBe(false)});
  it.each(["memory","sqlite"] as const)("mantiene semántica en %s",async(kind)=>{const{service}=system(kind);const p=await service.preparePublicReadModel(prepare);expect((await service.getPublicReadModel({context,publicRecordId:p.readModel.publicRecordId}))).toEqual(p)});
  it("reabre SQLite temporal y limpia auxiliares",async()=>{const dir=await mkdtemp(path.join(tmpdir(),"buholex-11l-")),db=path.join(dir,"exposicion.sqlite");try{const x=system("sqlite",db);const p=await x.service.preparePublicReadModel(prepare);await x.service.close();closers.splice(closers.indexOf(x.service),1);const y=system("sqlite",db);expect((await y.service.getPublicReadModel({context,publicRecordId:p.readModel.publicRecordId})).readModel.recordId).toBe("record-11l")}finally{await Promise.all(closers.splice(0).map((x)=>x.close()));await rm(dir,{recursive:true,force:true})}});
  it("cierra idempotentemente y falla seguro después",async()=>{const{service}=system();await service.close();await service.close();await expect(service.evaluateExposure(evaluate)).rejects.toMatchObject({code:"RESOURCE_CLOSED"})});
 });
 describe("readiness y barreras estáticas",()=>{
  it("mantiene toda exposición productiva deshabilitada",()=>{expect(evaluateJurisprudencePublicExposureReadiness()).toMatchObject({publicReadModelContractReady:true,realPublicExposurePresent:false,publicSearchConnected:false,sitemapConnected:false,robotsExposureEnabled:false,endpointsMounted:false,uiConnected:false,published:false,deployed:false,overrideSupported:false})});
  it("no monta rutas ni conexión jurisprudencial",async()=>{const root=process.cwd();await expect(readFile(path.join(root,"app","api"))).rejects.toBeDefined();const pkg=await readFile(path.join(root,"package.json"),"utf8");expect(pkg).toContain('"react": "19.1.6"');const page=await readFile(path.join(root,"app","jurisprudencia","page.tsx"),"utf8");expect(page).not.toMatch(/public-exposure|publication-execution/)});
  it("preserva productos y servicios comerciales",async()=>{const root=process.cwd(),services=await readFile(path.join(root,"data","services.ts"),"utf8"),catalog=await readFile(path.join(root,"data","template-catalog.ts"),"utf8");expect(services).toContain("allowsImmediatePayment: false");expect(services).toContain("published: false");expect(catalog).toContain('availabilityStatus: "editorial_preview"');expect(catalog).toContain("publicDownloadAuthorized: false")});
 });
});
