import type { JurisprudencePublicReadModelRepository } from "@/types/jurisprudence-public-exposure";

export type JurisprudenceSearchDocumentStatus = "prepared_internal" | "indexed_internal" | "withdrawn" | "superseded";
export type JurisprudenceSearchOperation = "prepare_document" | "index_document" | "search" | "withdraw_document" | "supersede_document" | "get_document" | "get_history";
export type JurisprudenceSearchSort = "relevance" | "issued_desc" | "issued_asc" | "title_asc";
export interface JurisprudenceSearchContext { readonly requestId:string; readonly actorReference:string; readonly requestedAt:string }
export interface JurisprudenceSearchDocument {
 readonly searchDocumentId:string; readonly publicRecordId:string; readonly recordId:string; readonly recordVersion:number; readonly publicRevision:number;
 readonly slug:string; readonly title:string; readonly caseNumber:string; readonly resolutionNumber:string; readonly resolutionType:string; readonly institutionName:string; readonly issuingBody:string; readonly matter:string; readonly issuedAt:string; readonly summary:string; readonly sourceName:string; readonly sourceDocumentId:string|null;
 readonly normalizedText:string; readonly normalizedTokens:readonly string[]; readonly institutionKey:string; readonly issuingBodyKey:string; readonly matterKey:string; readonly resolutionTypeKey:string;
 readonly schemaVersion:1; readonly status:JurisprudenceSearchDocumentStatus; readonly revision:number; readonly preparedAt:string; readonly indexedAt:string|null; readonly withdrawnAt:string|null; readonly supersededAt:string|null; readonly supersededByDocumentId:string|null;
 readonly realSearchIndex:false; readonly publiclySearchable:false; readonly externallyIndexed:false; readonly deployed:false;
}
export interface PrepareJurisprudenceSearchDocumentCommand { readonly context:JurisprudenceSearchContext; readonly publicRecordId:string; readonly expectedPublicRevision:number; readonly idempotencyKey:string }
export interface IndexJurisprudenceSearchDocumentCommand { readonly context:JurisprudenceSearchContext; readonly searchDocumentId:string; readonly expectedRevision:number; readonly idempotencyKey:string }
export type JurisprudenceSearchWithdrawalReason="public_exposure_withdrawn"|"rights_review_required"|"privacy_review_required"|"institutional_withdrawal";
export interface WithdrawJurisprudenceSearchDocumentCommand extends IndexJurisprudenceSearchDocumentCommand { readonly reason:JurisprudenceSearchWithdrawalReason }
export interface SupersedeJurisprudenceSearchDocumentCommand extends IndexJurisprudenceSearchDocumentCommand { readonly replacementPublicRecordId:string; readonly replacementExpectedPublicRevision:number }
export interface JurisprudenceSearchFilters { readonly institutionName?:string; readonly issuingBody?:string; readonly matter?:string; readonly resolutionType?:string; readonly issuedFrom?:string; readonly issuedTo?:string; readonly caseNumber?:string; readonly resolutionNumber?:string }
export interface JurisprudenceSearchQuery { readonly context:JurisprudenceSearchContext; readonly text?:string; readonly filters:JurisprudenceSearchFilters; readonly sort:JurisprudenceSearchSort; readonly offset:number; readonly limit:number }
export interface JurisprudenceSearchMatch { readonly searchDocumentId:string; readonly publicRecordId:string; readonly slug:string; readonly title:string; readonly caseNumber:string; readonly resolutionNumber:string; readonly resolutionType:string; readonly institutionName:string; readonly issuingBody:string; readonly matter:string; readonly issuedAt:string; readonly summary:string; readonly sourceName:string; readonly sourceDocumentId:string|null; readonly recordVersion:number; readonly score:number; readonly matchedBy:readonly ("case_exact"|"resolution_exact"|"title_exact"|"prefix"|"terms"|"filters")[] }
export interface JurisprudenceSearchResult { readonly items:readonly JurisprudenceSearchMatch[]; readonly total:number; readonly offset:number; readonly limit:number; readonly hasMore:boolean; readonly querySummary:{readonly textProvided:boolean;readonly filterCount:number;readonly sort:JurisprudenceSearchSort}; readonly realPublicSearch:false }
export type JurisprudenceSearchEventType="search_document_prepared"|"search_document_indexed"|"search_document_withdrawn"|"search_document_superseded";
export interface JurisprudenceSearchEvent { readonly eventId:string;readonly searchDocumentId:string;readonly recordId:string;readonly recordVersion:number;readonly revision:number;readonly sequence:number;readonly type:JurisprudenceSearchEventType;readonly occurredAt:string;readonly payload:Readonly<Record<string,string|number|boolean|null>> }
export interface JurisprudenceSearchDocumentView { readonly document:JurisprudenceSearchDocument; readonly activeForInternalQueries:boolean; readonly realSearchIndex:false; readonly publicSearchConnected:false; readonly externallyIndexed:false; readonly deployed:false }
export interface JurisprudenceSearchIdempotencyEntry { readonly idempotencyKey:string;readonly commandFingerprint:string;readonly result:JurisprudenceSearchDocumentView }
export interface JurisprudenceSearchCreateCommit { readonly document:JurisprudenceSearchDocument;readonly event:JurisprudenceSearchEvent;readonly idempotency:JurisprudenceSearchIdempotencyEntry }
export interface JurisprudenceSearchUpdateCommit extends JurisprudenceSearchCreateCommit { readonly expectedRevision:number }
export interface JurisprudenceSearchIndexRepository { findById(id:string):Promise<JurisprudenceSearchDocument|null>;findActiveByPublicRecord(publicRecordId:string):Promise<JurisprudenceSearchDocument|null>;listIndexed():Promise<readonly JurisprudenceSearchDocument[]>;listHistory(recordId:string):Promise<readonly JurisprudenceSearchEvent[]>;findIdempotencyResult(key:string):Promise<JurisprudenceSearchIdempotencyEntry|null>;create(commit:JurisprudenceSearchCreateCommit):Promise<void>;update(commit:JurisprudenceSearchUpdateCommit):Promise<void>;close():Promise<void> }
export type JurisprudenceSearchErrorCode="VALIDATION_ERROR"|"NOT_FOUND"|"SOURCE_NOT_ELIGIBLE"|"DOCUMENT_NOT_INDEXED"|"DOCUMENT_ALREADY_INDEXED"|"IDEMPOTENCY_CONFLICT"|"REVISION_CONFLICT"|"RESOURCE_CLOSED"|"REPOSITORY_UNAVAILABLE";
export interface JurisprudenceSearchLogEvent {readonly requestId:string;readonly operation:JurisprudenceSearchOperation;readonly resultCode:string;readonly documentReference?:string;readonly revision?:number;readonly resultCount?:number;readonly timestamp:string}
export interface JurisprudenceSearchLogger {log(event:JurisprudenceSearchLogEvent):void}
export interface JurisprudencePublicSearchDependencies {readonly publicReadModels:JurisprudencePublicReadModelRepository;readonly indexRepository:JurisprudenceSearchIndexRepository;readonly now:()=>string;readonly generateId:()=>string;readonly logger?:JurisprudenceSearchLogger}
export interface JurisprudencePublicSearchIndexService {prepare(input:unknown):Promise<JurisprudenceSearchDocumentView>;index(input:unknown):Promise<JurisprudenceSearchDocumentView>;search(input:unknown):Promise<JurisprudenceSearchResult>;withdraw(input:unknown):Promise<JurisprudenceSearchDocumentView>;supersede(input:unknown):Promise<JurisprudenceSearchDocumentView>;get(input:unknown):Promise<JurisprudenceSearchDocumentView>;getHistory(input:unknown):Promise<readonly JurisprudenceSearchEvent[]>;close():Promise<void>}
export type JurisprudencePublicSearchReadinessBlocker="real_public_exposure_missing"|"production_index_store_missing"|"authentication_missing"|"public_route_not_authorized"|"public_search_ui_missing"|"rate_limiting_missing"|"abuse_controls_missing"|"privacy_review_missing"|"monitoring_missing"|"sitemap_and_robots_not_authorized"|"real_data_missing"|"deployment_missing";
export interface JurisprudencePublicSearchReadiness {readonly searchIndexArchitectureReady:true;readonly internalSearchReady:true;readonly inMemoryAdapterReadyForTesting:true;readonly sqliteAdapterReadyForTesting:true;readonly productionSearchReady:false;readonly realSearchIndexPresent:false;readonly publicSearchConnected:false;readonly searchEndpointMounted:false;readonly searchUiConnected:false;readonly externalIndexingEnabled:false;readonly sitemapConnected:false;readonly robotsModified:false;readonly authenticationReal:false;readonly published:false;readonly deployed:false;readonly overrideSupported:false;readonly blockers:readonly JurisprudencePublicSearchReadinessBlocker[]}
