import { assertPublicExposureRepositoryOpen, clonePublicExposure, clonePublicExposureEvent, clonePublicExposureIdempotency, clonePublicReadModel, isActivePublicExposure, JurisprudencePublicExposureError } from "@/lib/jurisprudence-public-exposure-repository";
import type { JurisprudencePublicExposure, JurisprudencePublicExposureCreateCommit, JurisprudencePublicExposureEvent, JurisprudencePublicExposureIdempotencyEntry, JurisprudencePublicExposureRepository, JurisprudencePublicExposureUpdateCommit, JurisprudencePublicReadModel, JurisprudencePublicReadModelRepository } from "@/types/jurisprudence-public-exposure";

export class InMemoryJurisprudencePublicExposureRepository implements JurisprudencePublicExposureRepository {
  readonly #exposures = new Map<string, JurisprudencePublicExposure>(); readonly #models = new Map<string, JurisprudencePublicReadModel>(); readonly #events = new Map<string, JurisprudencePublicExposureEvent[]>(); readonly #keys = new Map<string, JurisprudencePublicExposureIdempotencyEntry>(); #closed = false;
  private open() { assertPublicExposureRepositoryOpen(this.#closed); }
  async findByPublicRecordId(id: string) { this.open(); const v = this.#exposures.get(id); return v ? clonePublicExposure(v) : null; }
  async findActiveByRecordVersion(id: string, version: number) { this.open(); const v = [...this.#exposures.values()].find((x) => x.recordId === id && x.recordVersion === version && isActivePublicExposure(x)); return v ? clonePublicExposure(v) : null; }
  async findLatestByRecordVersion(id: string, version: number) { this.open(); const v = [...this.#exposures.values()].filter((x) => x.recordId === id && x.recordVersion === version).sort((a,b) => b.updatedAt.localeCompare(a.updatedAt))[0]; return v ? clonePublicExposure(v) : null; }
  async listHistory(id: string) { this.open(); return [...this.#events.values()].flat().filter((x) => x.recordId === id).map(clonePublicExposureEvent); }
  async findIdempotencyResult(key: string) { this.open(); const v = this.#keys.get(key); return v ? clonePublicExposureIdempotency(v) : null; }
  async create(c: JurisprudencePublicExposureCreateCommit) { this.open(); if (this.#exposures.has(c.readModel.publicRecordId) || this.#models.has(c.readModel.publicRecordId)) throw new JurisprudencePublicExposureError("REVISION_CONFLICT", "El read model ya existe."); if (this.#keys.has(c.idempotency.idempotencyKey)) throw new JurisprudencePublicExposureError("IDEMPOTENCY_CONFLICT", "La clave ya existe."); this.#models.set(c.readModel.publicRecordId, clonePublicReadModel(c.readModel)); this.#exposures.set(c.readModel.publicRecordId, clonePublicExposure(c.exposure)); this.#events.set(c.exposure.exposureId, [clonePublicExposureEvent(c.event)]); this.#keys.set(c.idempotency.idempotencyKey, clonePublicExposureIdempotency(c.idempotency)); }
  async update(c: JurisprudencePublicExposureUpdateCommit) { this.open(); if (this.#keys.has(c.idempotency.idempotencyKey)) throw new JurisprudencePublicExposureError("IDEMPOTENCY_CONFLICT", "La clave ya existe."); const current = this.#exposures.get(c.readModel.publicRecordId); if (!current) throw new JurisprudencePublicExposureError("NOT_FOUND", "No existe la exposición."); if (current.revision !== c.expectedRevision) throw new JurisprudencePublicExposureError("REVISION_CONFLICT", "La revisión cambió."); const events = this.#events.get(current.exposureId); if (!events || c.event.sequence !== events.length + 1) throw new JurisprudencePublicExposureError("REVISION_CONFLICT", "La secuencia es inválida."); this.#models.set(c.readModel.publicRecordId, clonePublicReadModel(c.readModel)); this.#exposures.set(c.readModel.publicRecordId, clonePublicExposure(c.exposure)); events.push(clonePublicExposureEvent(c.event)); this.#keys.set(c.idempotency.idempotencyKey, clonePublicExposureIdempotency(c.idempotency)); }
  async findReadModelById(id: string) { this.open(); const v = this.#models.get(id); return v ? clonePublicReadModel(v) : null; }
  async findActiveReadModel(id: string, version: number) { this.open(); const v = [...this.#models.values()].find((x) => x.recordId === id && x.recordVersion === version && x.publicStatus === "exposed"); return v ? clonePublicReadModel(v) : null; }
  async listReadModels(id: string) { this.open(); return [...this.#models.values()].filter((x) => x.recordId === id).map(clonePublicReadModel); }
  async findReadModelBySlug(slug: string) { this.open(); const v = [...this.#models.values()].find((x) => x.slug === slug && x.publicStatus === "exposed" && x.exposedPublicly === true && x.withdrawnAt === null && x.supersededAt === null); return v ? clonePublicReadModel(v) : null; }
  async close() { this.#closed = true; }
}
export class InMemoryJurisprudencePublicReadModelRepository implements JurisprudencePublicReadModelRepository { constructor(readonly source: InMemoryJurisprudencePublicExposureRepository) {} findById(id:string){return this.source.findReadModelById(id)} findActiveByRecordVersion(id:string,v:number){return this.source.findActiveReadModel(id,v)} findActiveBySlug(slug:string){return this.source.findReadModelBySlug(slug)} listByRecord(id:string){return this.source.listReadModels(id)} async close(){} }
