import { createHash } from "node:crypto";
import { buildJurisprudencePublicReadModel } from "@/lib/jurisprudence-public-read-model-builder";
import { clonePublicExposureView, JurisprudencePublicExposureError } from "@/lib/jurisprudence-public-exposure-repository";
import { evaluateJurisprudencePublicExposureCommandSchema, exposeJurisprudencePublicReadModelCommandSchema, jurisprudencePublicExposureHistoryQuerySchema, jurisprudencePublicExposureQuerySchema, prepareJurisprudencePublicReadModelCommandSchema, supersedeJurisprudencePublicExposureCommandSchema, withdrawJurisprudencePublicExposureCommandSchema } from "@/lib/schemas/jurisprudence-public-exposure";
import { jurisprudencePublicProjectionSchema } from "@/lib/schemas/jurisprudence-publication-execution";
import type { EvaluateJurisprudencePublicExposureCommand, JurisprudencePublicExposure, JurisprudencePublicExposureBlocker, JurisprudencePublicExposureDependencies, JurisprudencePublicExposureEvent, JurisprudencePublicExposureEvaluation, JurisprudencePublicExposureService, JurisprudencePublicExposureView, JurisprudencePublicReadModel } from "@/types/jurisprudence-public-exposure";
import type { JurisprudencePublicationExecutionView } from "@/types/jurisprudence-publication-execution";

const slug=/^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const fingerprint=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
export function createJurisprudencePublicExposureService(d:JurisprudencePublicExposureDependencies):JurisprudencePublicExposureService{
 let closed=false; const open=()=>{if(closed)throw new JurisprudencePublicExposureError("RESOURCE_CLOSED","El servicio está cerrado.")};
 const context=(c:{requestId:string;actorReference:string;requestedAt:string})=>({requestId:c.requestId,actor:{kind:"internal_test" as const,id:c.actorReference},operationSource:"internal_api" as const,requestedAt:c.requestedAt});
 const log=(operation: Parameters<NonNullable<typeof d.logger>["log"]>[0]["operation"],resultCode:string,c:{requestId:string;requestedAt:string},v?:JurisprudencePublicExposureView)=>d.logger?.log({requestId:c.requestId,operation,resultCode,...(v?{publicRecordId:v.readModel.publicRecordId,recordVersion:v.readModel.recordVersion,publicRevision:v.readModel.publicRevision}:{}),timestamp:d.now()});
 async function evaluate(command:EvaluateJurisprudencePublicExposureCommand):Promise<JurisprudencePublicExposureEvaluation>{
   const blockers:JurisprudencePublicExposureBlocker[]=[]; let view:JurisprudencePublicationExecutionView;
   try{view=await d.execution.getExecution({context:command.context,executionId:command.executionId})}catch{blockers.push("execution_missing");return {status:"blocked",blockers:Object.freeze(blockers),realPublicExposure:false}}
   const {execution,projection}=view; if(execution.status!=="executed"||!view.current||!view.publicationExecuted)blockers.push("execution_not_current"); if(projection.status==="withdrawn")blockers.push("internal_projection_withdrawn");if(projection.status==="superseded")blockers.push("internal_projection_superseded");if(projection.status!=="active_internal")blockers.push("internal_projection_missing");
   if(!jurisprudencePublicProjectionSchema.safeParse(projection).success)blockers.push("internal_fields_present");
   let record:{readonly id:string;readonly recordVersion:number}|undefined;try{record=(await d.api.getInternalRecord({context:context(command.context),id:execution.recordId})).record}catch{blockers.push("record_id_mismatch")}
   if(record&&record.id!==execution.recordId)blockers.push("record_id_mismatch");if(!record||record.recordVersion!==command.expectedRecordVersion||execution.recordVersion!==command.expectedRecordVersion||projection.recordVersion!==command.expectedRecordVersion)blockers.push("record_version_mismatch");
   try{const a=await d.authorization.getAuthorizationCase({context:command.context,authorizationCaseId:execution.authorizationCaseId});const c=a.authorizationCase;if(c.recordId!==execution.recordId)blockers.push("record_id_mismatch");if(c.recordVersion!==execution.recordVersion)blockers.push("record_version_mismatch");if(c.status==="revoked")blockers.push("authorization_revoked");else if(c.status==="superseded")blockers.push("authorization_superseded");else if(c.expiresAt!==undefined&&c.expiresAt<=command.context.requestedAt)blockers.push("authorization_expired");else if(c.status!=="authorized"||!a.authorizationCurrent||!a.publicationAuthorizationGranted)blockers.push("authorization_not_current")}catch{blockers.push("authorization_missing")}
   try{const g=await d.governance.getDossier({context:command.context,dossierId:execution.publicationDossierId});const dossier=g.dossier;if(dossier.recordId!==execution.recordId)blockers.push("record_id_mismatch");if(dossier.recordVersion!==execution.recordVersion)blockers.push("record_version_mismatch");if(dossier.rightsAssessment?.status!=="public_display_permitted")blockers.push("rights_not_cleared","source_not_publicly_permitted");if(dossier.privacyAssessment?.status!=="approved_for_public_projection")blockers.push("privacy_not_cleared");if(!dossier.integrityAssessment||["not_checked","integrity_conflict"].includes(dossier.integrityAssessment.status))blockers.push("integrity_not_cleared");if(dossier.publicProjectionAssessment?.status!=="approved")blockers.push("public_review_not_current")}catch{blockers.push("rights_not_cleared","privacy_not_cleared")}
   if(projection.slug===null)blockers.push("slug_missing");else if(!slug.test(projection.slug))blockers.push("slug_invalid");if(projection.summary===null||projection.summary.trim()==="")blockers.push("summary_missing");if(projection.sourceName.trim()==="")blockers.push("source_not_publicly_permitted");
   const latest=await d.exposureRepository.findLatestByRecordVersion(execution.recordId,execution.recordVersion);if(latest?.status==="exposed")return{status:"already_exposed",publicRecordId:latest.publicRecordId,blockers:["active_exposure_exists"],realPublicExposure:false};if(latest?.status==="withdrawn")return{status:"withdrawn",publicRecordId:latest.publicRecordId,blockers:["internal_projection_withdrawn"],realPublicExposure:false};if(latest?.status==="superseded")return{status:"superseded",publicRecordId:latest.publicRecordId,blockers:["internal_projection_superseded"],realPublicExposure:false};
   return blockers.length?{status:"blocked",blockers:Object.freeze([...new Set(blockers)]),realPublicExposure:false}:{status:"ready",blockers:[],realPublicExposure:false};
 }
 async function replay(key:string,fp:string){const saved=await d.exposureRepository.findIdempotencyResult(key);if(!saved)return null;if(saved.commandFingerprint!==fp)throw new JurisprudencePublicExposureError("IDEMPOTENCY_CONFLICT","La clave fue usada con otro comando.");return clonePublicExposureView(saved.result)}
 const view=(readModel:JurisprudencePublicReadModel,exposure:JurisprudencePublicExposure):JurisprudencePublicExposureView=>Object.freeze({readModel,exposure,activeForTests:exposure.status==="exposed",realPublicExposure:false,publicSearchConnected:false,indexed:false,deployed:false});
 const event=(type:JurisprudencePublicExposureEvent["type"],e:JurisprudencePublicExposure,m:JurisprudencePublicReadModel,at:string,sequence:number):JurisprudencePublicExposureEvent=>Object.freeze({eventId:d.generateId(),exposureId:e.exposureId,publicRecordId:m.publicRecordId,recordId:m.recordId,recordVersion:m.recordVersion,publicRevision:m.publicRevision,sequence,type,occurredAt:at,payload:Object.freeze({status:m.publicStatus})});
 async function current(publicRecordId:string){const [m,e]=await Promise.all([d.readModelRepository.findById(publicRecordId),d.exposureRepository.findByPublicRecordId(publicRecordId)]);if(!m||!e)throw new JurisprudencePublicExposureError("NOT_FOUND","No existe el read model público.");return{m,e}}
 return {
  async evaluateExposure(input){open();const p=evaluateJurisprudencePublicExposureCommandSchema.safeParse(input);if(!p.success)throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Comando de evaluación inválido.");const r=await evaluate(p.data);log("evaluate_exposure",r.status,p.data.context);return r},
  async preparePublicReadModel(input){open();const p=prepareJurisprudencePublicReadModelCommandSchema.safeParse(input);if(!p.success)throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Comando de preparación inválido.");const fp=fingerprint(p.data),saved=await replay(p.data.idempotencyKey,fp);if(saved)return saved;const ev=await evaluate(p.data);if(ev.status!=="ready")throw new JurisprudencePublicExposureError("EXPOSURE_BLOCKED","La exposición no está lista.");const source=await d.execution.getExecution({context:p.data.context,executionId:p.data.executionId});const now=d.now(),m=buildJurisprudencePublicReadModel({publicRecordId:d.generateId(),projection:source.projection,preparedAt:now});const e:JurisprudencePublicExposure=Object.freeze({exposureId:d.generateId(),publicRecordId:m.publicRecordId,executionId:source.execution.executionId,authorizationCaseId:source.execution.authorizationCaseId,recordId:m.recordId,recordVersion:m.recordVersion,status:"prepared_internal",revision:1,createdAt:now,updatedAt:now,exposedAt:null,withdrawnAt:null,supersededAt:null,supersededByRecordVersion:null,realPublicExposure:false,indexed:false,deployed:false});const r=view(m,e);await d.exposureRepository.create({readModel:m,exposure:e,event:event("public_read_model_prepared",e,m,now,1),idempotency:{idempotencyKey:p.data.idempotencyKey,commandFingerprint:fp,result:r}});log("prepare_public_read_model","OK",p.data.context,r);return r},
  async expose(input){open();const p=exposeJurisprudencePublicReadModelCommandSchema.safeParse(input);if(!p.success)throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Comando de exposición inválido.");const fp=fingerprint(p.data),saved=await replay(p.data.idempotencyKey,fp);if(saved)return saved;const {m,e}=await current(p.data.publicRecordId);if(e.revision!==p.data.expectedRevision)throw new JurisprudencePublicExposureError("REVISION_CONFLICT","La revisión cambió.");const ev=await evaluate({context:p.data.context,executionId:e.executionId,expectedRecordVersion:e.recordVersion});if(ev.status!=="ready")throw new JurisprudencePublicExposureError("EXPOSURE_BLOCKED","La exposición no está lista.");const now=d.now(),nm=Object.freeze({...m,publicStatus:"exposed" as const,exposedAt:now,publicRevision:m.publicRevision+1,exposedPublicly:true}),ne=Object.freeze({...e,status:"exposed" as const,revision:e.revision+1,updatedAt:now,exposedAt:now}),r=view(nm,ne);await d.exposureRepository.update({readModel:nm,exposure:ne,event:event("public_exposure_activated",ne,nm,now,(await d.exposureRepository.listHistory(e.recordId)).length+1),idempotency:{idempotencyKey:p.data.idempotencyKey,commandFingerprint:fp,result:r},expectedRevision:p.data.expectedRevision});return r},
  async withdraw(input){open();const p=withdrawJurisprudencePublicExposureCommandSchema.safeParse(input);if(!p.success)throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Comando de retiro inválido.");const fp=fingerprint(p.data),saved=await replay(p.data.idempotencyKey,fp);if(saved)return saved;const {m,e}=await current(p.data.publicRecordId);if(e.revision!==p.data.expectedRevision)throw new JurisprudencePublicExposureError("REVISION_CONFLICT","La revisión cambió.");if(e.status!=="exposed")throw new JurisprudencePublicExposureError("EXPOSURE_NOT_CURRENT","La exposición no está vigente.");const now=d.now(),nm=Object.freeze({...m,publicStatus:"withdrawn" as const,withdrawnAt:now,publicRevision:m.publicRevision+1,exposedPublicly:false}),ne=Object.freeze({...e,status:"withdrawn" as const,revision:e.revision+1,updatedAt:now,withdrawnAt:now}),r=view(nm,ne);await d.exposureRepository.update({readModel:nm,exposure:ne,event:event("public_exposure_withdrawn",ne,nm,now,(await d.exposureRepository.listHistory(e.recordId)).length+1),idempotency:{idempotencyKey:p.data.idempotencyKey,commandFingerprint:fp,result:r},expectedRevision:p.data.expectedRevision});return r},
  async supersede(input){open();const p=supersedeJurisprudencePublicExposureCommandSchema.safeParse(input);if(!p.success)throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Comando de supersesión inválido.");const fp=fingerprint(p.data),saved=await replay(p.data.idempotencyKey,fp);if(saved)return saved;const {m,e}=await current(p.data.publicRecordId);if(e.revision!==p.data.expectedRevision||p.data.newRecordVersion<=e.recordVersion)throw new JurisprudencePublicExposureError("REVISION_CONFLICT","La revisión o nueva versión es inválida.");const record=(await d.api.getInternalRecord({context:context(p.data.context),id:e.recordId})).record;if(record.recordVersion!==p.data.newRecordVersion)throw new JurisprudencePublicExposureError("REVISION_CONFLICT","La nueva versión no es vigente.");const now=d.now(),nm=Object.freeze({...m,publicStatus:"superseded" as const,supersededAt:now,publicRevision:m.publicRevision+1,exposedPublicly:false}),ne=Object.freeze({...e,status:"superseded" as const,revision:e.revision+1,updatedAt:now,supersededAt:now,supersededByRecordVersion:p.data.newRecordVersion}),r=view(nm,ne);await d.exposureRepository.update({readModel:nm,exposure:ne,event:event("public_exposure_superseded",ne,nm,now,(await d.exposureRepository.listHistory(e.recordId)).length+1),idempotency:{idempotencyKey:p.data.idempotencyKey,commandFingerprint:fp,result:r},expectedRevision:p.data.expectedRevision});return r},
  async getPublicReadModel(input){open();const p=jurisprudencePublicExposureQuerySchema.safeParse(input);if(!p.success)throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Consulta inválida.");const {m,e}=await current(p.data.publicRecordId);return view(m,e)},
  async getHistory(input){open();const p=jurisprudencePublicExposureHistoryQuerySchema.safeParse(input);if(!p.success)throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Consulta inválida.");return d.exposureRepository.listHistory(p.data.recordId)},
  async close(){if(closed)return;closed=true;await d.readModelRepository.close();await d.exposureRepository.close()}
 }
}
