import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { assertPublicExposureRepositoryOpen, clonePublicExposure, clonePublicExposureEvent, clonePublicExposureIdempotency, clonePublicReadModel, jurisprudencePublicExposureSqliteMigration001, JurisprudencePublicExposureError } from "@/lib/jurisprudence-public-exposure-repository";
import { jurisprudencePublicExposureEventSchema, jurisprudencePublicExposureSchema, jurisprudencePublicExposureViewSchema, jurisprudencePublicReadModelSchema } from "@/lib/schemas/jurisprudence-public-exposure";
import type { JurisprudencePublicExposure, JurisprudencePublicExposureCreateCommit, JurisprudencePublicExposureEvent, JurisprudencePublicExposureRepository, JurisprudencePublicExposureUpdateCommit, JurisprudencePublicReadModel, JurisprudencePublicReadModelRepository } from "@/types/jurisprudence-public-exposure";

function value(row: unknown, key: string): unknown { if (!row || typeof row !== "object" || Array.isArray(row)) throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE", "Fila inválida."); return Reflect.get(row,key); }
function text(row: unknown,key:string):string { const v=value(row,key); if(typeof v!=="string") throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE","Dato inválido."); return v; }
function json(raw:string):unknown { try{return JSON.parse(raw)}catch{throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE","JSON inválido.")} }
function model(row:unknown):JurisprudencePublicReadModel { const p=jurisprudencePublicReadModelSchema.safeParse(json(text(row,"payload_json"))); if(!p.success) throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE","Read model inválido."); return clonePublicReadModel(p.data); }
function exposure(row:unknown):JurisprudencePublicExposure { const p=jurisprudencePublicExposureSchema.safeParse(json(text(row,"payload_json"))); if(!p.success) throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE","Exposición inválida."); return clonePublicExposure(p.data); }
function event(row:unknown):JurisprudencePublicExposureEvent { const p=jurisprudencePublicExposureEventSchema.safeParse(json(text(row,"payload_json"))); if(!p.success) throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE","Evento inválido."); return clonePublicExposureEvent(p.data); }
export class SqliteJurisprudencePublicExposureRepository implements JurisprudencePublicExposureRepository {
  readonly #db: DatabaseSync; #closed=false;
  constructor(databasePath:string){ if(databasePath!==":memory:"){const p=path.resolve(databasePath).replaceAll("\\","/").toLowerCase();if(["/public/","/app/","/components/","/data/"].some((x)=>p.includes(x)))throw new JurisprudencePublicExposureError("VALIDATION_ERROR","Ubicación pública prohibida.")} this.#db=new DatabaseSync(databasePath);this.#db.exec("PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;");if(databasePath!==":memory:")this.#db.exec("PRAGMA journal_mode=WAL;");this.#db.exec(jurisprudencePublicExposureSqliteMigration001); }
  private safe<T>(fn:()=>T):T{assertPublicExposureRepositoryOpen(this.#closed);try{return fn()}catch(e){if(e instanceof JurisprudencePublicExposureError)throw e;throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE","Falló la persistencia de exposición.")}}
  private tx(fn:()=>void){this.#db.exec("BEGIN IMMEDIATE");try{fn();this.#db.exec("COMMIT")}catch(e){this.#db.exec("ROLLBACK");throw e}}
  async findByPublicRecordId(id:string){return this.safe(()=>{const r=this.#db.prepare("SELECT payload_json FROM jurisprudence_public_exposures WHERE public_record_id=?").get(id);return r===undefined?null:exposure(r)})}
  async findActiveByRecordVersion(id:string,v:number){return this.safe(()=>{const r=this.#db.prepare("SELECT payload_json FROM jurisprudence_public_exposures WHERE record_id=? AND record_version=? AND status='exposed' LIMIT 1").get(id,v);return r===undefined?null:exposure(r)})}
  async findLatestByRecordVersion(id:string,v:number){return this.safe(()=>{const r=this.#db.prepare("SELECT payload_json FROM jurisprudence_public_exposures WHERE record_id=? AND record_version=? ORDER BY rowid DESC LIMIT 1").get(id,v);return r===undefined?null:exposure(r)})}
  async listHistory(id:string){return this.safe(()=>this.#db.prepare("SELECT payload_json FROM jurisprudence_public_exposure_events WHERE record_id=? ORDER BY rowid").all(id).map(event))}
  async findIdempotencyResult(key:string){return this.safe(()=>{const r=this.#db.prepare("SELECT command_fingerprint,result_json FROM jurisprudence_public_exposure_idempotency WHERE idempotency_key=?").get(key);if(r===undefined)return null;const p=jurisprudencePublicExposureViewSchema.safeParse(json(text(r,"result_json")));if(!p.success)throw new JurisprudencePublicExposureError("REPOSITORY_UNAVAILABLE","Resultado idempotente inválido.");return clonePublicExposureIdempotency({idempotencyKey:key,commandFingerprint:text(r,"command_fingerprint"),result:p.data})})}
  private insert(c:JurisprudencePublicExposureCreateCommit){this.#db.prepare("INSERT INTO jurisprudence_public_read_models VALUES(?,?,?,?,?)").run(c.readModel.publicRecordId,c.readModel.recordId,c.readModel.recordVersion,c.readModel.publicStatus,JSON.stringify(c.readModel));this.#db.prepare("INSERT INTO jurisprudence_public_exposures VALUES(?,?,?,?,?,?,?)").run(c.exposure.exposureId,c.exposure.publicRecordId,c.exposure.recordId,c.exposure.recordVersion,c.exposure.status,c.exposure.revision,JSON.stringify(c.exposure));this.#db.prepare("INSERT INTO jurisprudence_public_exposure_events VALUES(?,?,?,?,?)").run(c.event.eventId,c.event.exposureId,c.event.recordId,c.event.sequence,JSON.stringify(c.event));this.#db.prepare("INSERT INTO jurisprudence_public_exposure_idempotency VALUES(?,?,?)").run(c.idempotency.idempotencyKey,c.idempotency.commandFingerprint,JSON.stringify(c.idempotency.result))}
  async create(c:JurisprudencePublicExposureCreateCommit){this.safe(()=>this.tx(()=>this.insert(c)))}
  async update(c:JurisprudencePublicExposureUpdateCommit){this.safe(()=>this.tx(()=>{const current=this.#db.prepare("SELECT revision FROM jurisprudence_public_exposures WHERE public_record_id=?").get(c.readModel.publicRecordId);if(current===undefined)throw new JurisprudencePublicExposureError("NOT_FOUND","No existe la exposición.");if(value(current,"revision")!==c.expectedRevision)throw new JurisprudencePublicExposureError("REVISION_CONFLICT","La revisión cambió.");this.#db.prepare("UPDATE jurisprudence_public_read_models SET status=?,payload_json=? WHERE public_record_id=?").run(c.readModel.publicStatus,JSON.stringify(c.readModel),c.readModel.publicRecordId);this.#db.prepare("UPDATE jurisprudence_public_exposures SET status=?,revision=?,payload_json=? WHERE public_record_id=?").run(c.exposure.status,c.exposure.revision,JSON.stringify(c.exposure),c.exposure.publicRecordId);this.#db.prepare("INSERT INTO jurisprudence_public_exposure_events VALUES(?,?,?,?,?)").run(c.event.eventId,c.event.exposureId,c.event.recordId,c.event.sequence,JSON.stringify(c.event));this.#db.prepare("INSERT INTO jurisprudence_public_exposure_idempotency VALUES(?,?,?)").run(c.idempotency.idempotencyKey,c.idempotency.commandFingerprint,JSON.stringify(c.idempotency.result))}))}
  async findReadModelById(id:string){return this.safe(()=>{const r=this.#db.prepare("SELECT payload_json FROM jurisprudence_public_read_models WHERE public_record_id=?").get(id);return r===undefined?null:model(r)})}
  async findActiveReadModel(id:string,v:number){return this.safe(()=>{const r=this.#db.prepare("SELECT payload_json FROM jurisprudence_public_read_models WHERE record_id=? AND record_version=? AND status='exposed' LIMIT 1").get(id,v);return r===undefined?null:model(r)})}
  async listReadModels(id:string){return this.safe(()=>this.#db.prepare("SELECT payload_json FROM jurisprudence_public_read_models WHERE record_id=? ORDER BY rowid").all(id).map(model))}
  async findReadModelBySlug(slug:string){return this.safe(()=>{const rows=this.#db.prepare("SELECT payload_json FROM jurisprudence_public_read_models WHERE status='exposed'").all();for(const row of rows){const m=model(row);if(m.slug===slug&&m.exposedPublicly===true&&m.withdrawnAt===null&&m.supersededAt===null)return m}return null})}
  async close(){if(this.#closed)return;this.#closed=true;this.#db.close()}
}
export class SqliteJurisprudencePublicReadModelRepository implements JurisprudencePublicReadModelRepository { constructor(readonly source:SqliteJurisprudencePublicExposureRepository){} findById(id:string){return this.source.findReadModelById(id)} findActiveByRecordVersion(id:string,v:number){return this.source.findActiveReadModel(id,v)} findActiveBySlug(slug:string){return this.source.findReadModelBySlug(slug)} listByRecord(id:string){return this.source.listReadModels(id)} async close(){} }
