import type { JurisprudenceNewRecord } from "@/types/jurisprudence-repository";

export function createFictitiousJurisprudenceRecord(seed: number): JurisprudenceNewRecord {
  const marker = String(seed).padStart(3, "0");
  return {
    slug: `fixture-no-publicable-${marker}`,
    editorialStatus: "draft",
    publicationStatus: "private",
    caseNumber: `TEST-NO-REAL-EXP-${marker}`,
    resolutionNumber: `TEST-NO-REAL-RES-${marker}`,
    resolutionType: "Resolución ficticia para prueba de repositorio",
    institution: {
      id: "test-institution-not-real",
      name: "Institución ficticia exclusiva para pruebas",
      shortName: "Institución TEST",
      country: "Perú",
      kind: "judiciary",
      officialHomepage: null,
    },
    issuingBody: "Órgano ficticio exclusivo para pruebas",
    instanceLevel: "Instancia de prueba",
    specialty: seed % 2 === 0 ? "Civil de prueba" : "Constitucional de prueba",
    matter: seed % 2 === 0 ? "Materia contractual ficticia" : "Materia procesal ficticia",
    submatter: null,
    judicialDistrict: null,
    chamberOrCourt: "Sala ficticia no atribuible a casos reales",
    rapporteur: null,
    issuedAt: `2026-01-${String((seed % 20) + 1).padStart(2, "0")}`,
    officiallyPublishedAt: null,
    officialContent: {
      officialSummary: null,
      officialFullText: null,
      fullTextAvailable: false,
      publicationAllowed: false,
      documentAvailability: "metadata_only",
      originFormat: "pdf",
      language: "es-PE",
      pageCount: null,
    },
    editorialContent: {
      editorialTitle: `Registro ficticio no publicable ${marker}`,
      editorialSummary: "Resumen ficticio usado solo para comprobar persistencia local.",
      publicExcerpt: null,
      legalIssue: null,
      mainCriterion: null,
      relevantGrounds: [],
      decision: null,
      citedNorms: [],
      citedPrecedentIds: [],
      relatedRecordIds: [],
      keywords: ["fixture", `marker-${marker}`],
    },
    generatedContent: { internalDraft: null, reviewed: false, supportedBySource: false },
    authority: {
      resolutionCategory: "other",
      legalAuthority: "unknown",
      authorityEvidence: null,
      authorityVerifiedAt: null,
      validityStatus: "unknown",
      validityEvidence: null,
    },
    source: {
      type: "editorial_upload",
      name: "Fuente ficticia no verificada para pruebas",
      url: null,
      documentId: `TEST-DOC-NO-REAL-${marker}`,
      publishedAt: null,
      retrievedAt: null,
      checksum: null,
      verificationStatus: "unverified",
      verifiedAt: null,
      verifiedBy: null,
      verificationNotes: "Fixture no publicable.",
      evidenceReference: null,
    },
    officialFile: null,
    search: {
      normalizedSearchText: `registro ficticio ${marker} materia prueba órgano test`,
      normalizedMatters: [seed % 2 === 0 ? "materia contractual ficticia" : "materia procesal ficticia"],
      normalizedBodies: ["órgano ficticio exclusivo para pruebas"],
      jurisdiction: "Perú",
      tags: ["fixture"],
      editorialRelevance: seed,
    },
    internal: {
      editorialNotes: ["Fixture exclusivo de tests; nunca publicable."],
      contradictions: [],
      generatedContentOnly: false,
    },
  };
}
